'use client';

import { useParams } from 'next/navigation';
import { Camera, CheckCircle2, FileImage, Printer } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import PhotoCapture from '@/components/PhotoCapture';
import { getSample, saveSample, uploadEvidence } from '@/lib/store';
import { PhotoEvidence, RuptureEvent, Sample } from '@/lib/types';
import { formatDate, pressureMpa, physicalLocationByDate } from '@/lib/utils';

export default function SampleDetail(){
 const {id}=useParams<{id:string}>(); const [sample,setSample]=useState<Sample>(); const [active,setActive]=useState<string>(); const [files,setFiles]=useState<Record<string,File|undefined>>({}); const [load,setLoad]=useState(''); const [unit,setUnit]=useState<'kN'|'tf'|'kgf'|'N'>('kN'); const [diameter,setDiameter]=useState('100'); const [height,setHeight]=useState('200'); const [saving,setSaving]=useState(false);
 useEffect(()=>{getSample(id).then(s=>{setSample(s);setActive(s?.ruptures.find(r=>r.status!=='concluido')?.id)})},[id]);
 const rupture=sample?.ruptures.find(r=>r.id===active); const calc=useMemo(()=>pressureMpa(Number(load),unit,Number(diameter)),[load,unit,diameter]);
 if(!sample) return <div className="panel">Carregando amostra...</div>;
 async function finish(){ if(!rupture || !files.rompimento || !files.prensa || !files.cpFinal || !load || !diameter) return; setSaving(true); const photos:PhotoEvidence[]=[]; for(const key of ['rompimento','prensa','cpFinal'] as const){const f=files[key]; if(!f)continue; const url=await uploadEvidence(f,`samples/${sample.id}/ruptura-${rupture.ageDays}`); photos.push({key,url,name:key,createdAt:new Date().toISOString()});}
   const updatedR:RuptureEvent={...rupture,status:'concluido',load:Number(load),loadUnit:unit,diameterMm:Number(diameter),heightMm:Number(height),resistanceMpa:calc,completedAt:new Date().toISOString(),photos:[...rupture.photos,...photos]};
   const ruptures=sample.ruptures.map(r=>r.id===rupture.id?updatedR:r); const next=ruptures.find(r=>r.status!=='concluido'); const updated:Sample={...sample,ruptures,physicalLocation:next?physicalLocationByDate(next.dueDate):'Arquivo Encerrado',status:next?'em_andamento':'concluido',updatedAt:new Date().toISOString()}; await saveSample(updated); setSample(updated); setFiles({}); setLoad(''); setActive(next?.id); setSaving(false);
 }
 const stages=[{label:'Recebimento',date:sample.receivedAt,done:true},{label:'Moldagem',date:sample.moldedAt,done:true},...sample.ruptures.map(r=>({label:`Ruptura ${r.ageDays} dias`,date:r.dueDate,done:r.status==='concluido'})),{label:'Relatório final',date:'',done:sample.status==='concluido'}];
 return <div className="page-stack print-area"><section className="page-heading no-print"><div><span className="eyebrow">AMOSTRA {sample.labelBase}</span><h1>Rastreabilidade da amostra</h1><p>{sample.workName} • {sample.cpQuantity} CPs</p></div><button className="button secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimir</button></section>
 <section className="panel trace-head"><div><span>Etiqueta</span><strong>{sample.labelBase}</strong><small>{sample.cpLabels.join(' • ')}</small></div><div><span>Obra</span><b>{sample.workName}</b><small>Moldagem: {formatDate(sample.moldedAt)}</small></div><div><span>Local físico da ficha</span><b>{sample.physicalLocation}</b><small>Atualizado pelo fluxo</small></div></section>
 <section className="panel"><div className="timeline">{stages.map((s,i)=><div key={i} className={s.done?'done':''}><span>{s.done?<CheckCircle2 size={16}/>:i+1}</span><b>{s.label}</b><small>{s.date?formatDate(s.date):'Após encerramento'}</small></div>)}</div></section>
 <section className="panel"><div className="panel-header"><div><h2>Evidências iniciais</h2><p>Imagens obrigatórias registradas no cadastro.</p></div><FileImage/></div><div className="evidence-strip">{sample.photos.map(p=><figure key={p.key}><img src={p.url} alt={p.name}/><figcaption>{p.name}</figcaption></figure>)}</div></section>
 <section className="two-columns rupture-work no-print"><div className="panel"><div className="panel-header"><div><h2>Lançar ruptura</h2><p>Selecione uma idade e registre resultado + evidências.</p></div></div><div className="rupture-tabs">{sample.ruptures.map(r=><button key={r.id} className={`${active===r.id?'active':''} ${r.status==='concluido'?'completed':''}`} onClick={()=>setActive(r.id)}>{r.ageDays} dias <small>{formatDate(r.dueDate)}</small></button>)}</div>{rupture?.status==='concluido'?<div className="success-box"><CheckCircle2/><b>Ruptura concluída</b><span>{rupture.resistanceMpa?.toFixed(2)} MPa • {rupture.load} {rupture.loadUnit}</span></div>:<><div className="form-grid compact"><label>Carga da prensa *<input type="number" step="0.01" value={load} onChange={e=>setLoad(e.target.value)}/></label><label>Unidade *<select value={unit} onChange={e=>setUnit(e.target.value as any)}><option>kN</option><option>tf</option><option>kgf</option><option>N</option></select></label><label>Diâmetro CP (mm) *<input type="number" value={diameter} onChange={e=>setDiameter(e.target.value)}/></label><label>Altura CP (mm)<input type="number" value={height} onChange={e=>setHeight(e.target.value)}/></label></div><div className="result-preview"><span>Resultado preliminar</span><strong>{calc ? calc.toFixed(2) : '—'} MPa</strong><small>Força ÷ área circular. Conferência técnica obrigatória.</small></div><div className="photo-grid three"><PhotoCapture label="Foto do rompimento" value={files.rompimento} onChange={f=>setFiles({...files,rompimento:f})}/><PhotoCapture label="Foto da prensa" value={files.prensa} onChange={f=>setFiles({...files,prensa:f})}/><PhotoCapture label="Foto final do CP" value={files.cpFinal} onChange={f=>setFiles({...files,cpFinal:f})}/></div><button className="button primary full" disabled={saving||!files.rompimento||!files.prensa||!files.cpFinal||!load||!diameter} onClick={finish}>{saving?'Salvando...':'Concluir ruptura e mover ficha'}</button></>}</div>
 <div className="panel"><div className="panel-header"><div><h2>Histórico das rupturas</h2><p>Dados consolidados desta amostra.</p></div><Camera/></div><div className="history-list">{sample.ruptures.map(r=><div key={r.id}><div><b>{r.ageDays} dias</b><span>{formatDate(r.dueDate)}</span></div><div><span className={`status ${r.status}`}>{r.status.replace('_',' ')}</span>{r.resistanceMpa && <strong>{r.resistanceMpa.toFixed(2)} MPa</strong>}</div></div>)}</div></div></section>
 <section className="report-sheet"><div className="report-brand"><img src="/logo-solocontrol.png"/><div><h2>Relatório Gerencial da Amostra</h2><span>Solocontrol Lab</span></div></div><div className="report-grid"><div><span>Obra</span><b>{sample.workName}</b></div><div><span>Etiqueta</span><b>{sample.labelBase}</b></div><div><span>Moldagem</span><b>{formatDate(sample.moldedAt)}</b></div><div><span>Tipo</span><b>{sample.sampleType}</b></div></div><table><thead><tr><th>Idade</th><th>Data</th><th>Carga</th><th>Resultado</th><th>Status</th></tr></thead><tbody>{sample.ruptures.map(r=><tr key={r.id}><td>{r.ageDays} dias</td><td>{formatDate(r.dueDate)}</td><td>{r.load?`${r.load} ${r.loadUnit}`:'—'}</td><td>{r.resistanceMpa?`${r.resistanceMpa.toFixed(2)} MPa`:'—'}</td><td>{r.status}</td></tr>)}</tbody></table><p className="report-note">Relatório gerencial do sistema. A emissão técnica oficial deve seguir os procedimentos e aprovações internas da Solocontrol.</p></section>
 </div>
}
